- name: Copying local files
  ansible.builtin.copy:
    src: "docker"
    dest: "~/shadowsocks_config"


- name: Setting config.json file
  template:
    src: "shadowsocks-config.j2"
    dest: "~/shadowsocks_config/docker/shadowsocks/config.json"


- name: Building shadowsocks service
  docker_compose:
    project_src: "~/shadowsocks_config/docker"
    build: yes
    services: "shadowsocks"
  register: output


- name: Restarting shadowsocks service
  docker_compose:
    project_src: "~/shadowsocks_config/docker"
    restarted: yes
    services: "shadowsocks"
  register: output
